<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Daftar_mhs_model extends CI_Model
{

    public $table = 'daftar_mhs';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by('nama', 'ASC');
        return $this->db->get($this->table)->result();
    }
    function get_all_ikhwan()
    {
        $this->db->order_by('nama', 'ASC');
        $this->db->where_not_in('j_k',array('P'));
        return $this->db->get($this->table)->result();
    }

    function get_all_akhwat()
    {
        $this->db->order_by('nama', 'ASC');
        $this->db->where_not_in('j_k',array('L'));
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('npm', $q);
	$this->db->or_like('fakultas', $q);
	$this->db->or_like('jurusan', $q);
	$this->db->or_like('semester', $q);
	$this->db->or_like('kamar', $q);
	$this->db->or_like('operator', $q);
	$this->db->or_like('noHP', $q);
	$this->db->or_like('j_k', $q);
	$this->db->or_like('tgl_lahir', $q);
	$this->db->or_like('ttl', $q);
	$this->db->or_like('sertifikat_ldik', $q);
	$this->db->or_like('foto', $q);
	$this->db->or_like('bahasa', $q);
	$this->db->or_like('hobi', $q);
	$this->db->or_like('keahlian', $q);
	$this->db->or_like('cita_cita', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('npm', $q);
	$this->db->or_like('fakultas', $q);
	$this->db->or_like('jurusan', $q);
	$this->db->or_like('semester', $q);
	$this->db->or_like('kamar', $q);
	$this->db->or_like('operator', $q);
	$this->db->or_like('noHP', $q);
	$this->db->or_like('j_k', $q);
	$this->db->or_like('tgl_lahir', $q);
	$this->db->or_like('ttl', $q);
	$this->db->or_like('sertifikat_ldik', $q);
	$this->db->or_like('foto', $q);
	$this->db->or_like('bahasa', $q);
	$this->db->or_like('hobi', $q);
	$this->db->or_like('keahlian', $q);
	$this->db->or_like('cita_cita', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Daftar_mhs_model.php */
/* Location: ./application/models/Daftar_mhs_model.php */
/* Please DO NOT modify this information : */
/* Generated by Sebuahhobi 2018-12-31 17:50:59 */